<?php

namespace App\Future\BillOfLadingResource;

use Adminftr\Table\Future\Components\Filters\SelectFilter;
use Adminftr\Table\Future\Components\Filters\TextFilter;
use Adminftr\Table\Future\Components\Headers\Actions\ResetAction;
use Adminftr\Widgets\Future\Widgets\Widget;
use App\Future\ContractResource\Modal\ViewContract;
use App\Models\Contract;
use App\Models\User;
use Adminftr\Table\Future\BaseTable;
use Adminftr\Table\Future\Components\Actions\Action;
use Adminftr\Table\Future\Components\Actions\Actions;
use Adminftr\Table\Future\Components\Columns\TextColumn;
use Adminftr\Table\Future\Components\FilterInput;
use Adminftr\Table\Future\Components\Filters\DateFilter;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;

class Table extends BaseTable
{
    protected string $model = Contract::class;

    protected function query(): Builder
    {
        return parent::query()->with(["user", "post"]); // TODO: Change the autogenerated stub
    }

    protected function columns(): array
    {
        return [
            TextColumn::make('id', __('ID'))->searchable()->sortable(),
            TextColumn::make('code', __('Mã HĐ'))->searchable()->sortable(),
            TextColumn::make('post.field', __('Lĩnh vực'))->badge(
                [],
                [
                    'leather_goods' => __('Hàng đã hoá'),
                    'clothing' => __('Quần áo'),
                    'all' => __('Tất cả'),
                ]
            ),
            TextColumn::make('created_at', __('Ngày tạo'))->sortable(),
            TextColumn::make('id_user_b', __('Người tạo'))->hide(),
            TextColumn::make('post_id', __('Người tạo'))->hide(),
            TextColumn::make('user.name', __('Người tạo')),
            TextColumn::make('user.phone', __('SĐT'))->isRelation(),
            TextColumn::make('status', __('Trạng thái'))->badge(
                [
                    'accepted' => 'success',
                    'pending' => 'warning',
                    'returned' => 'danger',
                    'cancel' => 'danger',
                ],
                [
                    'accepted' => __('Hoàn Thành'),
                    'pending' => __('Đợi khiếu nại'),
                    'returned' => __('Hoàn lại tiền'),
                    'cancel' => __('Huỷ'),
                ]
            )
        ];
    }

    protected function filters(): array
    {
        return [
            TextFilter::make('code', __('Mã HĐ')),
            SelectFilter::make('status', __('Trạng thái'))->options([
                ['id' => 'accepted', 'label' => 'Hoàn Thành'],
                ['id' => 'pending', 'label' => 'Đợi khiếu nại'],
                ['id' => 'returned', 'label' => 'Hoàn lại tiền'],
                ['id' => 'cancel', 'label' => 'Huỷ'],
            ]),
            DateFilter::make('created_at', __('Ngày tạo')),
        ];
    }

    protected function actions(Actions $actions): Actions
    {
        return $actions->create(
            [
                Action::make('edit', __('Sửa'), 'fas fa-edit')->modal(ViewContract::class,'edit'),
                Action::make('view', __('View'), 'fas fa-edit')->link(function ($data) {
                    return route('admin.contracts.edit', $data->id);
                })->size('font-size:20px;'),
            ]
        );
    }

    protected function headerActions(): array
    {
        return [
            ResetAction::make(),
        ];
    }

//    protected function widgets(): array
//    {
////        $count = $this->model::query()->count();
////
////        $widgetCountPermission = Widget::make($count.' Hợp đồng', '', 'fa fa-key');
////        $widgetCountPermission->setColor('green');
////        $widgetCountPermission->setCol(['md' => 5, 'xl' => 4]);
////
////        $countContract = Widget::make('Tổng số hợp đồng: 0', '')
////            ->callback(function ($widget) {
////                $count = $this->model::query()
////                    ->count();
////                $widget->title = "Tổng số hợp đồng: " . $count;
////                $widget->setIcon('fa fa-contract');
////                $widget->setCol(['md' => 6, 'xl' => 4]);
////            });
////
////        $countAccepted = Widget::make('Hơp đồng đã hoàn thành: 0', '')
////            ->callback(function ($widget) {
////                $count = $this->model::query()
////                    ->where('status', 'accepted')
////                    ->count();
////                $widget->title = "Hơp đồng đã hoàn thành: " . $count;
////                $widget->setIcon('fa fa-user-xmark');
////                $widget->setCol(['md' => 6, 'xl' => 4]);
////                $widget->setColor('red');
////            });
////
////        $countCancel = Widget::make('Hơp đồng bị huỷ: 0', '')
////            ->callback(function ($widget) {
////                $count = $this->model::query()
////                    ->where('status', 'cancel')
////                    ->count();
////                $widget->title = "Hơp đồng bị huỷ: " . $count;
////                //$widget->setIcon('fa fa-user-xmark');
////                $widget->setCol(['md' => 6, 'xl' => 4]);
////                $widget->setColor('red');
////            });
////
////        $sumMoneyNotPay = Widget::make('Tổng tiền không thanh toán: 0', '')
////            ->callback(function ($widget) {
////                $count = $this->model::query()
////                    ->where('status', 'cancel')
////                    ->count();
////                $widget->title = "Tổng tiền không thanh toán: " . $count;
////                //$widget->setIcon('fa fa-user-xmark');
////                $widget->setCol(['md' => 6, 'xl' => 4]);
////                $widget->setColor('red');
////            });
////
////        return [
////            $countContract,
////            $countCancel,
////            $countAccepted,
////            $sumMoneyNotPay
////        ];
//    }
}
