version: '3.8'

services:
    dragonfly:
        image: docker.dragonflydb.io/dragonflydb/dragonfly
        command: ["entrypoint.sh", "dragonfly"]
        ports:
            - "6379:6379"
        volumes:
            - dragonfly_data:/data

volumes:
    dragonfly_data:
