<?php

namespace App\Future\ContractResource;

use Adminftr\Table\Future\BaseTable;
use Adminftr\Table\Future\Components\Actions\Action;
use Adminftr\Table\Future\Components\Actions\Actions;
use Adminftr\Table\Future\Components\Columns\TextColumn;
use Adminftr\Table\Future\Components\Filters\DateFilter;
use Adminftr\Table\Future\Components\Filters\SelectFilter;
use Adminftr\Table\Future\Components\Headers\Actions\ResetAction;
use Adminftr\Widgets\Future\Stat;
use App\Models\Contract;
use Illuminate\Database\Eloquent\Builder;

class Table extends BaseTable
{
    protected string $model = Contract::class;
    public bool $canSelect = false;
    protected function columns(): array
    {
        return [TextColumn::make('id', __('ID'))->searchable()->sortable(),
            TextColumn::make('code', __('Mã HĐ'))->searchable()->sortable(),
            TextColumn::make('post.field', __('Lĩnh vực'))->badge([
                'leather_goods' => 'success',
                'clothing' => 'primary'
            ], ['leather_goods' => __('Hàng đã hoá'), 'clothing' => __('Quần áo'),
                'all' => __('Tất cả'),]), TextColumn::make('created_at', __('Ngày tạo'))->sortable(), TextColumn::make('id_user_b', __('Người tạo'))->hide(), TextColumn::make('post_id', __('Người tạo'))->hide(), TextColumn::make('user.name', __('Người tạo')), TextColumn::make('user.phone', __('SĐT'))->isRelation(), TextColumn::make('status', __('Trạng thái'))->badge(['accepted' => 'success', 'pending' => 'warning', 'returned' => 'danger', 'cancel' => 'danger', 'failed_to_pick' => 'danger',], ['accepted' => __('Hoàn Thành'), 'pending' => __('Đợi khiếu nại'), 'returned' => __('Hoàn lại tiền'), 'cancel' => __('Huỷ'),])];
    }

    protected function filters(): array
    {
        return [SelectFilter::make('status', __('Trạng thái'))->options([['id' => 'accepted', 'label' => 'Hoàn Thành'], ['id' => 'pending', 'label' => 'Đợi khiếu nại'], ['id' => 'returned', 'label' => 'Hoàn lại tiền'], ['id' => 'cancel', 'label' => 'Huỷ'],]), DateFilter::make('created_at', __('Ngày tạo')),];
    }

    protected function actions(Actions $actions): Actions
    {
        return $actions->create([Action::make('view', __('View'), 'fas fa-edit')->link(function ($data) {
                return route('admin.contracts.edit', $data->id);
            })]);
    }

    protected function headerActions(): array
    {
        return [ResetAction::make()];
    }

    protected function widgets(): array
    {
        $count = $this->model::query()->count();
        $countCancel = $this->model::query()->where('status', 'cancellation_requested')->count();
        $countSuccess = $this->model::query()->where('status', 'delivered_successfully')->count();
        $totalMoneySuccess = $this->model::query()->where('status', 'delivered_successfully')->sum('total_amount');
        return [Stat::make('Tổng số hợp đồng', $count)->description('Tổng số hợp đồng đã tạo'), Stat::make('Tổng số hợp đồng bị hủy', $countCancel)->description('Tổng số hợp đồng bị hủy'), Stat::make('Tổng số hợp đồng hoàn thành', $countSuccess)->description('Tổng số hợp đồng hoàn thành'), Stat::make('Tổng tiền hợp đồng hoàn thành', $totalMoneySuccess)->description('Tổng tiền hợp đồng hoàn thành'),];
    }

    protected function query(): Builder
    {
        return parent::query()->with(["user", "post"]); // TODO: Change the autogenerated stub
    }
}
