<?php

namespace App\Restify;

use Binaryk\LaravelRestify\Http\Requests\RestifyRequest;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Modules\Conversation\app\Models\Message;

class MessageRepository extends Repository
{
    public static string $model = Message::class;

    public static array $search = [
        'id',
        'content',
    ];

    public static array $sort = [
        'id',
        'content',
        'sender_id',
        'created_at',
        'updated_at',
    ];

    public static array $match = [
        'id' => 'integer',
        'sender_id' => 'integer',
        'content'=>'string',
    ];

    public static int $globalSearchResults = 10;

    public static function indexQuery(RestifyRequest $request, Relation|Builder $query)
    {
        $query->where('sender_id', $request->user()->id);
        return parent::indexQuery($request, $query); // TODO: Change the autogenerated stub
    }

    public function fields(RestifyRequest $request): array
    {
        return [
            id(),
            field('conversation_id')->rules('required'),
            field('sender_id')->rules('required'),
            field('reply_to_id'),
            field('content')->rules('required'),
            field('type')->rules('required'),
            field('attachment_url'),
            field('created_at'),
            field('updated_at'),
        ];
    }
}
