<?php

namespace App\Restify;

use App\Models\PartyAInfo;
use Binaryk\LaravelRestify\Http\Requests\RestifyRequest;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Relations\Relation;
use Illuminate\Support\Facades\Auth;

class PartyAInfoRepository extends Repository
{
    public static string $model = PartyAInfo::class;
    public static array $search = ['contract_id', 'account_number', 'email', 'bank_name', 'address', 'recipient_name'];
//    public static string $uriKey = 'partyainfos';
    public static function indexQuery(RestifyRequest $request, Relation|Builder $query)
    {
       $user = $request->user();
       $request->merge(['user_id' => $user->id]);
        return parent::indexQuery($request, $query); // TODO: Change the autogenerated stub
    }

    public function store(RestifyRequest $request)
    {
        $request->merge(['user_id' => $request->user()->id]);
        if (Auth::user()->type == 'seller') {
            return response()->json(['message' => 'Bạn không có quyền thực hiện hành động này'], 403);
        }
        if ($request->contract_id) {
            $contract = $request->user()->contracts()->find($request->contract_id);
            if (!$contract) {
               return response()->json(['message' => 'Hơp đồng không tồn tại'], 404);
            }
        }
        return parent::store($request); // TODO: Change the autogenerated stub
    }

    public function fields(RestifyRequest $request): array
    {
        return [
            id(),
            field('user_id'), // Add this line
            field('contract_id')->rules('required'),
            field('account_number')->rules('required'),
            field('email')->rules('email'),
            field('bank_name')->rules('required'),
            field('address')->rules('required'),
            field('recipient_name')->rules('required'),
            ];
    }
}
