<?php

	namespace App\Restify;

	use App\Models\PostImage;
    use Binaryk\LaravelRestify\Http\Requests\RestifyRequest;
	use Illuminate\Database\Eloquent\Builder;
	use Illuminate\Database\Eloquent\Relations\Relation;


    class PostImagesRepository extends Repository
	{
		public static string $model = PostImage::class;

		public static function indexQuery(RestifyRequest $request, Relation|Builder $query)
		{
			$query->whereHas('post', function ($query) {
				$query->where('status', 'published');
			});
			return parent::indexQuery($request, $query); // TODO: Change the autogenerated stub
		}

		public function fields(RestifyRequest $request): array
		{
			return [
				id(),
				field('post_id')->rules( 'required','exists:posts,id')->messages([
					'required' => 'Bài viết không được để trống',
					'exists' => 'Bài viết không tồn tại',
				]),
				field('image')->rules('required', 'image')->messages([
					'required' => 'Ảnh không được để trống',
					'image' => 'Ảnh không hợp lệ',
				])->image()->disk('public'),
				field('user_id')->storeCallback(function ($value) {
					return auth()->user()->id;
				})->updateCallback(function ($value) {
					return auth()->user()->id;
				}),
			];
		}

	}
